name: Build ARM image files
on:
  workflow_dispatch:
    inputs:
      host:
        type: choice
        description: "选择编译的镜像"
        options:
          - n1
          - tx3
          - x96maxplus
        required: true
        default: n1

env:
  NIX_PATH: nixpkgs=channel:nixos-unstable
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: SSH Private Key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install nixFlake
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = zenqy.cachix.org-1:G5csLBsu/kQIOXU7XUiqeMacwzN1WQWv0+GysTVmJgo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://zenqy.cachix.org/ https://cache.nixos.org/
            system-features = benchmark big-parallel nixos-test uid-range kvm

      - name: build image
        run: |
          echo "DATE=$(date +"%Y.%m%d.%H%M")" >> $GITHUB_ENV
          nix build .#${{ inputs.host }}
          echo '-------------'
          ls result
          if [[ -d result/sd-image ]]; then
            ls result/sd-image
          fi
      - name: Upload Image To Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          removeArtifacts: true
          tag: v${{ env.DATE }}
          artifacts: "result/*/*"
          body: |
            image:${{ inputs.host }}

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 3
          delete_workflows: true
          workflows_keep_day: 30
          gh_token: ${{ github.token }}
